require("configs.tree-sitter")
require("configs.nvim-tree")
require("configs.lsps")
-- require("configs.presence")
require("configs.ibl")
require("configs.autoclose")
require("configs.harpoon")
require("configs.telescope")
require("configs.lualine")
require("configs.alpha")
require("configs.trouble")
require("configs.persistence")
require("configs.nvim-ts-autotag")
require("configs.todo-comments")
require("configs.undotree")
require("configs.live-server")
