local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>sf', function()
    builtin.find_files({ file_ignore_patterns = { "node_modules", ".git", ".next" } })
end, {})
vim.keymap.set('n', '<leader>sg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>sb', builtin.buffers, {})
